# docker-compose.yml
services:
  backend:
    container_name: oss-chatbot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - PDF_DIR=/app/data
      - PROVIDER=${PROVIDER:-azure}
    volumes:
      - ./data:/app/data
      - ./hf_cache:/root/.cache/huggingface
    ports:
      - "8000:8000"
    command:
      - /bin/sh
      - -c
      - |
        python ./ingest.py || echo 'ingest failed/empty, continuing'
        python -m uvicorn main:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/ || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
    restart: unless-stopped
